language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

env:
  matrix:
    - PIP_FLAGS="--quiet --pre"
    - PIP_FLAGS="--quiet"

before_install:
  - python -m pip install ${PIP_FLAGS} --upgrade pip
  - python -m pip install ${PIP_FLAGS} -r requirements.txt
  - python -m pip install ${PIP_FLAGS} pytest coverage coveralls

install:
  - python -m pip install ${PIP_FLAGS} .

script:
  - python -m coverage run ./setup.py test
  - bash ci/test-bin.sh

after_success:
  - coveralls

cache:
  pip: true
